version: "3"

tasks:
  setup:
    desc: Setup environment
    cmds:
      - uv sync

  cli:
    cmds:
      - cmd: uv run -m celine.cli {{.CLI_ARGS}}
        silent: true

  cli-dbg:
    cmds:
      - task: clean-pycache
      - cmd: DEBUGGER=1 DEBUGGER_WAIT=0 uv run -m celine.cli {{.CLI_ARGS}}

  clean-pycache:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -r {} +

  integration-tests:
    desc: Run integration tests
    cmds:
      - cd integration-tests && task run -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  dump-source:
    cmds:
      - uv run python scripts/dump_source.py
