version: "3"

tasks:
  start:
    cmds:
      - docker compose up -d

  stop:
    cmds:
      - docker compose down

  reset:
    cmds:
      - docker compose down -v

  run:
    desc: Run integration tests
    cmds:
      - uv run pytest -vv -o log_cli=true --log-cli-level=DEBUG
